# Multi-provider model configuration
models:
  deepseek:
    provider: "autogen_ext.models.openai.OpenAIChatCompletionClient"
    config:
      model: "deepseek-chat"
      api_key: "${DEEPSEEK_API_KEY}"
      base_url: "https://api.deepseek.com"
      model_info:
        family: "deepseek"
        vision: false
        function_calling: true
        json_output: true
        structured_output: true
      
  moonshot:
    provider: "autogen_ext.models.openai.OpenAIChatCompletionClient"
    config:
      model: "moonshot-v1-8k"
      api_key: "${MOONSHOT_API_KEY}"
      base_url: "https://api.moonshot.cn/v1"
      model_info:
        family: "moonshot"
        vision: false
        function_calling: true
        json_output: true
        structured_output: true
      
  alibaba:
    provider: "autogen_ext.models.openai.OpenAIChatCompletionClient"
    config:
      model: "qwen-turbo"
      api_key: "${ALIBABA_API_KEY}"
      base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1"
      model_info:
        family: "qwen"
        vision: false
        function_calling: true
        json_output: true
        structured_output: true
      
  ollama:
    provider: "autogen_ext.models.openai.OpenAIChatCompletionClient"
    config:
      model: "llama2"
      api_key: "ollama"
      base_url: "${OLLAMA_BASE_URL:-http://localhost:11434/v1}"
      model_info:
        family: "llama"
        vision: false
        function_calling: false
        json_output: false
        structured_output: false
      
  openai:
    provider: "autogen_ext.models.openai.OpenAIChatCompletionClient"
    config:
      model: "gpt-4o"
      api_key: "${OPENAI_API_KEY}"
      model_info:
        family: "gpt"
        vision: true
        function_calling: true
        json_output: true
        structured_output: true

# Default model selections for agents
agent_models:
  code_generator: "deepseek"
  quality_checker: "alibaba"
  code_optimizer: "deepseek"
  user_proxy: "deepseek"